name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch: # manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'  # Specify the .NET 9 version

      - name: restore workloads
        run: dotnet workload restore

      - name: restore dependencies
        run: dotnet restore      
        
      - name: Build and Pack
        run: |
          chmod +x ./build.sh
          ./build.sh


      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-build-$(date +%Y-%m-%d)
          release_name: Nightly Build $(date +%Y-%m-%d)
          draft: false
          prerelease: true
          files: |
            ./bin/Release/net9.0/win10-x64/publish/*
            # ./bin/Release/net9.0/osx-x64/publish/*
            # ./bin/Release/net9.0/ios-arm64/publish/*
