name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch: # manual run
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore .NET MAUI Workloads
        run: |
          dotnet workload install maui-android
          dotnet workload install maui-desktop
          dotnet workload install maui-ios
          dotnet workload install maui-tizen
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Pack
        run: dotnet publish -f net9.0-windows10.0.26100.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./bin/Release/net9.0-windows10.0.26100.0/win10-x64/publish/*
          if-no-files-found: error
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build-output
          tag-name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: "Nightly build ${{ github.ref }}"
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "nightly"
#          prerelease: true
#          title: "Nightly Build"
#          files: ./bin/Release/net9.0-windows10.0.26100.0/win10-x64/*
