name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch: # manual run
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore .NET MAUI Workloads
        run: |
          dotnet workload install maui-android
          dotnet workload install maui-desktop
          dotnet workload install maui-ios
          dotnet workload install maui-tizen


      - name: Install dependencies
        run: |
          sudo apt-get install -y libgdk-pixbuf2.0-dev
          sudo apt-get install -y libgl-dev
          sudo apt-get install -y libsecret-1-dev

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Pack
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-build-$(date +%Y-%m-%d)
          release_name: Nightly Build $(date +%Y-%m-%d)
          draft: false
          prerelease: true
          files: |
            ./bin/Release/net9.0/win10-x64/publish/*
            # ./bin/Release/net9.0/osx-x64/publish/*
            # ./bin/Release/net9.0/ios-arm64/publish/*
